"""
routers/alerts.py
Endpoints:
  GET /alerts     — active alerts generated by reconcile.py
Implemented in Phase 4.
"""
from __future__ import annotations

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from auth import require_api_key
from database import get_db
from schemas import AlertSchema

router = APIRouter(dependencies=[Depends(require_api_key)])


@router.get("/", response_model=list[AlertSchema])
def list_alerts(db: Session = Depends(get_db)):
    """
    Run reconcile checks and return active alerts:
    benchmark drift, uncategorized trades, position age, concentration, loss streaks.
    """
    raise NotImplementedError("Implemented in Phase 4")
